services:
  app:
    build: .
    container_name: mongo_chat
    ports:
      - "8000:8000"
    volumes:
      - ./app:/code/app
    env_file:
      - .env
    command: 
      uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    restart:
      always